
p = simulinkproject;

%% Build the S-function
cd(fullfile(p.RootFolder,'CoSimExample','sfun'));

mex('-I..\util',...
    ['-I' fullfile(p.RootFolder,'libzmq','include')],...
    ['-I' fullfile(p.RootFolder,'cppzmq')],...
    ['-L' fullfile(p.RootFolder,'libzmq','bin')],...
    '-llibzmq','-llibzmq-v142-mt-4_3_4',...
    'statcalsfcngateway.cpp',...
    'statcalclient.cpp',...
    fullfile(p.RootFolder,'CoSimExample','util','statcal_util.cpp'));

%% Build Control S-function
cd(fullfile(p.RootFolder,'CoSimExample','sfun'));

mex('-I..\util',...
    ['-I' fullfile(p.RootFolder,'libzmq','include')],...
    ['-I' fullfile(p.RootFolder,'cppzmq')],...
    ['-L' fullfile(p.RootFolder,'libzmq','bin')],...
    '-llibzmq','-llibzmq-v142-mt-4_3_4',...
    'controlsfun.cpp',...
    'controlclient.cpp',...
    fullfile(p.RootFolder,'CoSimExample','util','statcal_util.cpp'));

cd(p.RootFolder)

%% Build Control Triple Pendulum S-function
cd(fullfile(p.RootFolder,'CoSimExample','sfun'));

mex('-I..\util',...
    ['-I' fullfile(p.RootFolder,'libzmq','include')],...
    ['-I' fullfile(p.RootFolder,'cppzmq')],...
    ['-L' fullfile(p.RootFolder,'libzmq','bin')],...
    '-llibzmq','-llibzmq-v142-mt-4_3_4',...
    'controluntriplnsfun.cpp',...
    'controluntriplnclient.cpp',...
    fullfile(p.RootFolder,'CoSimExample','util','statcal_util.cpp'));

cd(p.RootFolder)
